### ISSUE TITLE
Nest.js Tests

### ISSUE THREAD

**Issue by creadicted** [RobertYoung/mean-stack-typescript-docker#1]
hey! nice starter. Have you worked out how to get the tests running?

**Comment by RobertYoung** [comment]
I've fixed the errors you may have been getting.
`git pull`
`rm -rf server/node_modules`
`docker run -it --rm -v ${PWD}/server:/usr/src/app/server -w /usr/src/app/server mean-stack yarn`
`docker run -it --rm -v ${PWD}/:/usr/src/app/ -w /usr/src/app/server mean-stack npm run test`

**Comment by creadicted** [comment]
I was searching for demos that have actually some tests that work. Thank you that you took the time!
